server:
  port: 8080
  servlet:
    context-path: /api

spring:
 application:
   name: videoapi

 datasource:
   url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
   driverClassName: org.h2.Driver
   username: sa
   password: password
   hikari:
     pool-name: HikariCP
     maximum-pool-size: 10
     minimum-idle: 5

 liquibase:
   enabled: true
   change-log: classpath:db/db.changelog-master.yml

 jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
 h2:
   console:
     enabled: true
     path: /h2-console

 servlet:
   multipart:
     maxFileSize: 100MB
     maxRequestSize: 100MB
