name: Build application to DEV environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run tests
        run: mvn verify

      - name: Build Docker image (simulated)
        run: |
          echo "Simulating Docker image build for spring-boot-app."

      - name: Push Docker image to Docker Hub (simulated)
        run: |
          echo "Pushing Docker image build for spring-boot-app."    

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Helm install app on Kubernetes (simulated)
        run: |
          echo "Installing app on Kubernetes..."
            
